STAR-1422: Increase the schema agreement timeout in SAI tests to 60s
Addresses:

org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.cassandra.distributed.test.sai.SAIUtil that uses org.apache.cassandra.distributed.Cluster was not fulfilled within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
	at org.apache.cassandra.distributed.test.sai.SAIUtil.waitForSchemaAgreement(SAIUtil.java:128)
	at org.apache.cassandra.distributed.test.sai.SAIUtil.getIndexes(SAIUtil.java:117)

(cherry picked from commit 86ff718e2b7125afbe053a95f941e335aec1a748)
(cherry picked from commit ddfb15e33eba5a5b01dd739d2ecbe3e316ce9bd7)
(cherry picked from commit f6fa5194e5b2a5d584e0ab5a0fd18decd1fd1546)